name: 'Build Nominatim'

runs:
    using: "composite"

    steps:
        - name: Install prerequisits
          run: |
            sudo apt-get install -y -qq libboost-system-dev libboost-filesystem-dev libexpat1-dev zlib1g-dev libbz2-dev libpq-dev libproj-dev python3-psycopg2 python3-pyosmium python3-dotenv python3-psutil python3-jinja2
          shell: bash

        - name: Download dependencies
          run: |
              if [ ! -f country_grid.sql.gz ]; then
                  wget --no-verbose https://www.nominatim.org/data/country_grid.sql.gz
              fi
              cp country_grid.sql.gz Nominatim/data/country_osm_grid.sql.gz
          shell: bash

        - name: Configure
          run: mkdir build && cd build && cmake ../Nominatim
          shell: bash

        - name: Build
          run: |
              make -j2 all
              sudo make install
          shell: bash
          working-directory: build
