name: CI Tests

on: [ push, pull_request ]

jobs:
    tests:
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                postgresql: [9.5, 13]
                include:
                    - postgresql: 9.5
                      postgis: 2.5
                    - postgresql: 13
                      postgis: 3

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  tools: phpunit, phpcs

            - name: Get Date
              id: get-date
              run: |
                  echo "::set-output name=date::$(/bin/date -u "+%Y%W")"
              shell: bash

            - uses: actions/cache@v2
              with:
                  path: |
                     data/country_osm_grid.sql.gz
                     monaco-latest.osm.pbf
                  key: nominatim-data-${{ steps.get-date.outputs.date }}

            - uses: ./.github/actions/setup-postgresql
              with:
                  postgresql-version: ${{ matrix.postgresql }}
                  postgis-version: ${{ matrix.postgis }}
            - uses: ./.github/actions/build-nominatim

            - name: Install test prerequsites
              run: sudo apt-get install -y -qq php-codesniffer pylint python3-pytest python3-behave

            - name: PHP linting
              run: phpcs --report-width=120 .

            - name: Python linting
              run: pylint --extension-pkg-whitelist=osmium nominatim

            - name: PHP unit tests
              run: phpunit ./
              working-directory: test/php

            - name: Python unit tests
              run: py.test-3 test/python

            - name: BDD tests
              run: behave -DREMOVE_TEMPLATE=1 --format=progress3
              working-directory: test/bdd

    import:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true

            - name: Get Date
              id: get-date
              run: |
                  echo "::set-output name=date::$(/bin/date -u "+%Y%W")"
              shell: bash

            - uses: actions/cache@v2
              with:
                  path: |
                     data/country_osm_grid.sql.gz
                     monaco-latest.osm.pbf
                  key: nominatim-data-${{ steps.get-date.outputs.date }}

            - uses: ./.github/actions/setup-postgresql
              with:
                  postgresql-version: 13
                  postgis-version: 3
            - uses: ./.github/actions/build-nominatim

            - name: Prepare import environment
              run: |
                  mkdir data-env
                  cd data-env
                  if [ ! -f monaco-latest.osm.pbf ]; then
                      wget --no-verbose https://download.geofabrik.de/europe/monaco-latest.osm.pbf
                  fi
                  which nominatim
              shell: bash

            - name: Import
              run: nominatim import --osm-file monaco-latest.osm.pbf
              shell: bash
              working-directory: data-env

            - name: Import special phrases
              run: nominatim special-phrases --from-wiki | psql -d nominatim
              working-directory: data-env

            - name: Check import
              run: nominatim check-database
              working-directory: data-env

            - name: Run update
              run: |
                   nominatim replication --init
                   nominatim replication --once
              working-directory: data-env

            - name: Run reverse-only import
              run : nominatim import --osm-file ../monaco-latest.osm.pbf --reverse-only
              working-directory: data-env
              env:
                  NOMINATIM_DATABASE_DSN: pgsql:dbname=reverse
